In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore' )

dataset = pd.read_csv("Merged data set.csv")

In [2]:
dataset.drop('Date/Time', axis=1, inplace=True)

In [3]:
#Method 1
knn_dataset1 = (dataset - np.min(dataset))/(np.max(dataset) - np.min(dataset))
knn_dataset1

,Wind speed,Generator speed,Blade angle,Wind direction,Ambient temperature,Active power
0,0.283159,0.656031,0.482210,0.238414,0.757543,0.154425
1,0.270696,0.641372,0.482210,0.235277,0.758498,0.144650
2,0.263905,0.612932,0.482210,0.239505,0.758910,0.126554
3,0.242957,0.581847,0.482211,0.243410,0.756613,0.107886
4,0.272641,0.629971,0.482210,0.243410,0.755913,0.136821
...,...,...,...,...,...,...
51290,0.192364,0.519802,0.482064,0.514892,0.741817,0.052795
51291,0.154534,0.518462,0.482064,0.514892,0.742731,0.025888
51292,0.153430,0.518774,0.482064,0.514892,0.742365,0.028942
51293,0.160631,0.515419,0.482064,0.511263,0.740856,0.023918
51294,0.190883,0.517446,0.482064,0.498033,0.740418,0.049271

In [5]:
#Method 2
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler().fit(dataset)
knn_dataset2 = mms.transform(dataset)
knn_dataset2 = pd.DataFrame(knn_dataset2)
knn_dataset2

              0         1         2         3         4         5
0      0.283159  0.656031  0.482210  0.238414  0.757543  0.154425
1      0.270696  0.641372  0.482210  0.235277  0.758498  0.144650
2      0.263905  0.612932  0.482210  0.239505  0.758910  0.126554
3      0.242957  0.581847  0.482211  0.243410  0.756613  0.107886
4      0.272641  0.629971  0.482210  0.243410  0.755913  0.136821
...         ...       ...       ...       ...       ...       ...
51290  0.192364  0.519802  0.482064  0.514892  0.741817  0.052795
51291  0.154534  0.518462  0.482064  0.514892  0.742731  0.025888
51292  0.153430  0.518774  0.482064  0.514892  0.742365  0.028942
51293  0.160631  0.515419  0.482064  0.511263  0.740856  0.023918
51294  0.190883  0.517446  0.482064  0.498033  0.740418  0.049271

[51295 rows x 6 columns]

In [6]:
x = knn_dataset1.drop("Active power", axis = 1)
y = knn_dataset1["Active power"]

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 2)

In [19]:
from sklearn.neighbors import KNeighborsRegressor

knn_model = KNeighborsRegressor().fit(x_train, y_train)
y_pred = knn_model.predict(x_test)

In [20]:
predict_df = pd.DataFrame({"y_Test" : y_test, "y_Predicted" : y_pred})
predict_df.head()

         y_Test  y_Predicted
22645  0.783018     0.785465
18933  0.000607     0.000607
18075  0.092760     0.092545
26551  0.368619     0.369392
43618  0.000607     0.000607

In [25]:
predict_df = (predict_df*(np.max(dataset.displacement) - np.min(dataset.displacement))) + np.min(dataset.displacement)
predict_df.head()

AttributeError: 'DataFrame' object has no attribute 'displacement'