In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') #to filter warning messages

In [2]:
df=pd.read_csv('D_data.csv')
df.set_index("Date", inplace=True)
df.head()

,Wind speed,Generator speed,Blade angle,Wind direction,Ambient temperature,Active power
Date,,,,,,
1/1/2020,5.313541,11.770079,-0.561819,-351.656781,29.223170,259.196071
1/2/2020,5.483615,12.008322,-0.100172,-348.796442,29.447159,280.923954
1/3/2020,5.140796,11.467794,-0.776094,-351.823328,29.560999,231.064502
1/4/2020,4.368247,10.245036,-0.776035,-361.517685,29.573758,147.105333
1/5/2020,5.700915,12.506949,-0.776141,-362.518394,29.512227,296.006479

In [3]:
# Split data to features and target
from sklearn.model_selection import train_test_split
x=df.drop(['Active power'],axis=1)

# Feature scaling
from sklearn.preprocessing import StandardScaler
std_x=StandardScaler()
X=std_x.fit_transform(x)


y=df['Active power'].values.ravel()
#y=y.reshape(-1,1)


# Test Train split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=2)

In [4]:
from sklearn.neural_network import MLPRegressor
Model_MLP = MLPRegressor(hidden_layer_sizes=(100,100,100),activation="relu" ,solver="adam",learning_rate="constant",alpha=0.0001, max_iter=100)
Model_fit = Model_MLP.fit(x_train, y_train)

In [5]:
y_pred_MLP = Model_MLP.predict(x_test)
data_1 = pd.DataFrame({'Predicted value': y_pred_MLP, 'Real Value': y_test})
data_1.head(20)

    Predicted value  Real Value
0        282.200019  223.326349
1        594.855180  592.697148
2        618.020141  577.682788
3        962.479664  978.516872
4        194.194000  228.530926
5        830.129351  734.417792
6        822.595261  837.286927
7        195.402969  224.888789
8        212.856974  239.111992
9        253.936157  285.855145
10       580.167073  605.124944
11       158.611842  237.015174
12       756.281847  731.913437
13       148.974287  168.654513
14       591.480744  633.776396
15       617.610922  615.892121
16       638.040290  686.163801
17       438.848224  440.989678
18       111.442364  156.388351
19       752.056559  729.855474

In [6]:
from sklearn.metrics import accuracy_score,r2_score,mean_absolute_error, mean_squared_error

print('R2-score:',r2_score(y_test,y_pred_MLP))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_pred_MLP)))
print('MAE:',mean_absolute_error(y_test, y_pred_MLP))
print('MSE:',mean_squared_error(y_test, y_pred_MLP))

R2-score: 0.9728480127937353
RMSE: 55.03982700711763
MAE: 43.10732516292087
MSE: 3029.382556973435